---
title: "Пример Rmd ноутбука"
author: "Карпович Лидия"
date: "2023-08-31"
output: html_document
---

```{r}
remove.packages("flextable")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages(c("readr", "tibble", "dplyr", "tidyr", "flextable"))

library(readr)
library(tibble)
library(dplyr)
library(tidyr)
library(flextable)
```


```{r}
data <- read_tsv("C:/Users/79214/Downloads/data_tsv.tsv")
as_tibble(data)
```

```{r}
data %>% view()
```


```{r}
summary(data)
```
```{r}
psych::describe(data)

```
```{r}
prop.table(table(data$Группа, data$'Группа крови'))
```
```{r}
data_1 <- tibble(var_1 = "var 1", var_2 = "var 2", var_3 = "var 3")
data_2 <- tibble(var_1 = "var 1", var_2 = "var 2")
data_3 <- tibble(var_1 = "var 1", var_2 = "var 2")

data_1 %>% bind_rows(data_2) %>% bind_rows(data_3)
```
```{r}
data %>% group_by("Группа") %>% ungroup()
```

```{r}
data %>%
  split(~ `Группа`)
```

```{r}
data %>%
  select(`Группа крови`, `Рост`)
```
```{r}
data %>%
  select(`Группа`, where(is.numeric))
```

```{r}
data %>% select(contains("_E1"))
```

```{r}
data %>%
  slice_head(prop = 0.1)
```

```{r}
data %>%
  filter(`Группа крови` %in% c("A (II)", "O (I)") & `Группа` != "Группа 1")
```

```{r}
data %>%
  filter(if_all(.cols = contains("Базофилы"), .fns = function(x) x > 1.5))
```

```{r}
data %>%
  group_by(`Группа`) %>%
  filter(`Возраст` > 36)
```
```{r}
data %>%
  mutate(`Женщины с четвёртой группой крови` = ifelse(`Пол` == "Женский" & `Группа крови` == "AB (IV)", "Да", "Нет")) %>%
  select (`Женщины с четвёртой группой крови`, everything()) %>%
  arrange(`Женщины с четвёртой группой крови`)
```

```{r}
data %>%
  mutate(`Группа крови` = `Группа крови` %>% na_if("B (III)"))
```

```{r}
data %>%
  arrange(desc(`Рост`), `Возраст`)
```

```{r}
statistics <- list(
      `Количество субъектов` = ~length(.x),
      `Количество (есть данные)` = ~sum(!is.na(.x)),
      `Нет данных` = ~sum(is.na(.x)),
      `Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `95% ДИ для среднего` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.character(),
      `мин. - макс.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2))),
      `Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2)))
)

data %>%
  select(`Группа`, where(is.numeric)) %>%
  group_by(`Группа`) %>%
  summarise(across(where(is.numeric), statistics)) %>%
  pivot_longer(!`Группа`) %>%
  separate(name, into = c("Переменная", "Статистика"), sep = "__") %>%
  rename(`Значение` = value) %>%
  flextable() %>%
  theme_box() %Ю%
  merge_v(c("Группа", "Переменная"))

```

